### ISSUE TITLE
Moar stats

### ISSUE THREAD

**Issue by itsmeow** [antoinegag/curseforge-analytics-viewer#2]
![image](https://user-images.githubusercontent.com/10366817/53281392-a3880a80-36f5-11e9-8edc-5c43bb8e39d4.png)
![image](https://user-images.githubusercontent.com/10366817/53281394-aaaf1880-36f5-11e9-8418-c14624e10ec2.png)

- [x] Area graphs with curseforge/twitch downloads stacked
- [ ] Graph correlating points -> daily downloads
- [ ] Point derivatives 
![image](https://user-images.githubusercontent.com/10366817/53281404-daf6b700-36f5-11e9-818a-48dd2b92f267.png)

**Comment by antoinegag** [comment]
Thanks a lot 😄

**Comment by antoinegag** [comment]
There's no direct correlation between points and download so not going to bother.
