### ISSUE TITLE
Formatting of raw data is broken on mobile

### ISSUE THREAD

**Issue by strikerrocker** [antoinegag/curseforge-analytics-viewer#7]
![screenshot_2019-02-24-13-11-29-1](https://user-images.githubusercontent.com/28724985/53296497-1d271200-3836-11e9-8712-875860265b0e.png)
Title explains it all!!

**Comment by antoinegag** [comment]
I am not sure how this could be better formatted. It's kind of hard to fit a table that has multiple columns in a very narrow screen on mobile.

**Comment by antoinegag** [comment]
@strikerrocker Any suggestion?

**Comment by DarkGuardsman** [comment]
Wouldn't call that broken and title doesn't explain it all. Only suggestion I can offer would be to at least indent the data to make it easier to trace. As well add some short hand with each line to note what it means. Ex: 3.43CP

**Comment by strikerrocker** [comment]
My bad for not replying as i forgot r to write a reply. 
My suggestions is to shorten the data like date could be compressed into 09/03/19, etc and Make a horizontal table (keys on the columns) so you can scroll to the right and left to view the data
